#!/bin/bash
# Command line utility to start a program and monitor it
cmd=""
i="0"

while getopts ":b:" opt; do
  case ${opt} in
    b )
      target=$OPTARG
      if [ "$target" == "bitcount" ];then
			bin=0
		elif [ "$target" == "basicmath" ];then
			bin=1
		elif [ "$target" =="qsort" ];then
			bin=2
		else
			bin=-1
		fi
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      ;;
  esac
done

shift $((OPTIND -1))

for var in "$@"
do
    if [ $i = "0" ];
    then
    	i="1"
    	var="$(pwd)/${var}" 
    fi
    cmd="${cmd} ${var}"
     
done
echo "comando lanciato $cmd"
conf="instr_retired,unhalted_ref_cycles_fixed,cycles,instr,llc_references,llc_misses,branch_instr_retired"
pmctrack -o $cmd.out -T 1 -c $conf $cmd
python3 /home/sgundo/Desktop/Tesi/OS_FaultMonitor/ML/eval_proc.py $cmd $target
# pid=$!
# echo $pid
# echo "monitor lanciato"
#echo "$pid $bin" > /proc/monitor
